### PR TITLE
upgrade kafka offset monitor

### PR DESCRIPTION
**Pull request by ruseinov**
fixes https://app.asana.com/0/899562584103344/1166965223097457

### CODE REVIEW

**Comment by ruseinov** [comment]
It seems like the ```https://circleci.com/gh/mix/kafka-librato-monitor/edit#checkout``` key here is outdated, @alif @mattbernst if you could update the key - that'd be helpful for ci

**Comment by ruseinov** [comment]
Note: I had to find a 3rd party contributor who upgraded the original library, fork a repo and deploy that to our artifactory. Should work good tho.

**Comment by ruseinov** [comment]
@mix-dev ^^ whoever has permissions to update circleci deploy keys - please do!

**Comment by michaelshobbs** [comment]
@ruseinov updated the circle config. new failure occurred

**Comment by ruseinov** [comment]
@michaelshobbs that failure has been fixed by the workaround on local. Curious why it's emerging here

**Comment by ruseinov** [comment]
@michaelshobbs this needs more work, thanks to: https://github.com/sbt/sbt/issues/3618

**Comment by ruseinov** [comment]
Thanks for adding the ssh keys though, I will take it from here @michaelshobbs .

**Comment by ruseinov** [comment]
@michaelshobbs fixed!

**Review by michaelshobbs — APPROVED** [review]

**Comment by ruseinov** [comment]
@michaelshobbs you need write access to this, otherwise your approval does not count.
@alif I guess before merging this, seeing as how there is no automated deployment anywhere we will need to test it on dev anyway.

**Review by michaelshobbs — DISMISSED** [review]

**Comment by michaelshobbs** [comment]
@ruseinov how about now?

EDIT: I can also just merge it. Let me know

**Comment by ruseinov** [comment]
@michaelshobbs Nope, does not work. Let's first test if this works on dev once there is an environment to test against and then merge if it does I guess

**Comment by ruseinov** [comment]
I have tagged the previous version, so I guess we could merge now. It should actually work fine.

**Comment by ruseinov** [comment]
What bothers me is that after I decided to look into the commit history I can see that Ankit did a similar upgrade and then rolled it back.

I wonder why, possibly because we are using too old a version of kafka? In any case I can't see anything that deploys this, so I guess we'll need to deploy this manually somehow.

**Comment by ruseinov** [comment]
We went with another approach as the new kafka does not expose zookeeper and there is a plan to get rid of it for good. It's also not clear whether this would work properly as the upgrade failed to deliver once before.

**Pull request closed without merging**
